[package]
name = "day-22"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
kiss3d = "0.35.0"
rand = "0.8.5"
random_color = "0.8.0"
